### PR TITLE
Add wifi nvram and dhd kernel module load parameters

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by floion** [comment]
@telphan @agherzan @petrosagg

**Comment by floion** [comment]
Why would it be a bbappend to linux-firmware? This is not firmware, it's nvram settings.
Also, if other machines use it, they will be added to compatible machines list. There is no strong suspicion that other artik boards use the same wifi chipset.

**Comment by agherzan** [comment]
Indeed it is not a firmware but the nvram settings go there too. What I try to understand is if this nvram settings file is artik specific.

**Comment by floion** [comment]
It's specific to the wifi chipset.

**Comment by floion** [comment]
And this chipset is used on the artik5 and artik10. So it's board specific.
These are the boards we support in meta-artik. In the artik family, there is also another board, the artik1. That for example, lacks wifi. So why not list compatible machines then? So it will break/add unnecessary packages if/when another board like artik1 is added.

I don't understand what we are trying to change here and why.

**Comment by agherzan** [comment]
So this nvram configuration is not artik 5/10/X specific base on what you say. It just happens to be used by these boards because they come with a specific chip. So, my question then is, why don't we make this generic and let the machine.conf decide what if it needs to be included in MACHINE_EXTRA_RDEPENDS MACHINE_EXTRA_RECOMMENDS. If we go for the generic approach we either go for a another recipe as you did that would be machine independent or go with a bbappend to linux-firmware (prefer the first actually but independent and with a recipe name that specifies exactly the targeted chipset - there is a comment in the nvram settings file).  For the a new recipe:
1. I recommend a name like linux-firmware-bcm4354XXX - I don't know exactly the chipset name of which this configuration is relevant
2. This recipe should be inherit allarch http://www.yoctoproject.org/docs/2.1/ref-manual/ref-manual.html#ref-classes-allarch
3. there should be a version or revision of this configuration file - i see something in the file itself - please set PV

ref: http://git.yoctoproject.org/cgit/cgit.cgi/meta-rockchip/tree/recipes-kernel/linux-firmware-bcm-veyron/linux-firmware-bcm-veyron.bb

**Comment by floion** [comment]
Why would I do a bbappend for the linux firmware recipe? This is not firmware

Maybe Otavio will convince you:

https://github.com/Freescale/meta-fsl-arm-extra/tree/master/recipes-bsp/broadcom-nvram-config

**Comment by agherzan** [comment]
Quote from what I wrote: "prefer the first actually but independent and with a recipe name that specifies exactly the targeted chipset" while referring to having it as a separate recipe.

**Comment by floion** [comment]
Does it not say it's for the 4354 chipset?

**Comment by agherzan** [comment]
There is already firmware for 4353 in linux-firmware. Usually when you add a nvram or a firmware is because you need support for a specific variant of the cipset. So this change was done for a specific variant otherwise generic bcm driver and firmware for 4353 are already available.

**Comment by floion** [comment]
Andrei, I am writing this again. Firmware is firmware and firmware settings are firmware settings. We add just the nvram setting here (firmware settings). And I know there is already firmware for 4354 in linux-firmware, that is what I am using.
If you look in the recipe, you will see it has a:

RDEPENDS_${PN} = "linux-firmware-bcm4354"

Not sure what the issue is here

**Comment by agherzan** [comment]
1. nvram is on the wifi chip
2. the settings file is getting flashed in this nvram
3. the settings are machine specific because they might include configuration for things like antenna 
4. the kernel module flashes the nvram

**Comment by agherzan** [comment]
LGTM

**Pull request merged**
